name: Auto Deployment

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/**'

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Sigma CLI
      - name: Install Sigma CLI
        run: sudo npm i slappforge-sigma-cli -g

      # Builds project
      - name: Build Project
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: echo "::set-env name=DEPLOYMENT_PACKAGE::$(sigma aws build --s3Bucket udith.sigma.test --s3Prefix auto_builds --awsKey $AWS_ACCESS_KEY --awsSecret $AWS_SECRET_KEY)"

      - uses: actions/upload-artifact@v2
        with:
          name: deployment-package
          path: sigma_builds/build_*.zip

      # Deploy project
      - name: Deploy Project
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: sigma aws deploy --depPackage s3://udith.sigma.test/hello/build_CLITestProject_1.0.0_1594023578623.zip --awsKey $AWS_ACCESS_KEY --awsSecret $AWS_SECRET_KEY --autoDepMode true
